apiVersion: apps/v1
kind: Deployment
metadata: 
  name: first-deploy
  labels:
    app: nginx
spec: 
  replicas: 2
  selector: 
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: first-pod
          image: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "500M"
          ports:
            - containerPort: 80
      initContainers:
        - name: second-pod
          image: ubuntu
          command: ['mkdir initContainer']
