apiVersion: v1
kind: LimitRange
metadata:
  name: limit
spec:
  limits:
    - default:
        cpu: 
        memory:
      defaultRequests:
        cpu:
        memory:
      max:
        cpu:
        memory:
      min:
        cpu:
        memory: