apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq
spec:
  hard:
    pods: "5"
    # count/deployments.apps: "2"
    limits.cpu: 500m
    limits.memory: 500Mi
    requests.cpu: 100m
    requests.memory: 200Mi