apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: first
  name: first
spec:
  replicas: 3
  selector:
    matchLabels:
      app: first
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: first
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
