apiVersion: v1
kind: Pod
metadata:
  name: first-pod
  labels:
    app: first
spec:
  containers:
    - name: first-con
      image: nginx
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: 512m
          memory: 512Mi
        requests:
          cpu: 256m
          memory: 256Mi
