apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      nodeSelector:
        type: web
      containers:
      - image: nginx
        name: nginx
        resources: {}
        volumeMounts:
          - name: pvc
            mountPath: /data
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: demo-pvc
status: {}
