apiVersion: v1
kind: PersistentVolume
metadata: 
  name: demo-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: local-path
  local:
    path: /tmp/demo-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: type
            operator: In
            values:
              - web
