apiVersion: v1
kind: Service
metadata:
  name: nginx1-service
spec:
  selector:
    app: nginx
  ports:
  - port: {{ .Values.services.port }}
    targetPort: {{ .Values.services.targetPort }}
  type: {{ .Values.services.type }}

