apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: all-func-bind
  namespace: default
subjects:
  - kind: User
    name: pardium
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: all-func
  apiGroup: rbac.authorization.k8s.io
