apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-ability-bind
  namespace: default
subjects:
  - kind: ServiceAccount
    name: demo-sa
roleRef:
  kind: Role
  name: pod-ability
  apiGroup: rbac.authorization.k8s.io
