apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: first-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods,ns"]
    verbs: ["get","list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secondUser-role-bind
subjects:
  - kind: User
    name: second_user
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: first-role
  apiGroup: rbac.authorization.k8s.io

