apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  # nodeName: minikube-m02
  # nodeSelector:
  #   type: basic

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: type
                operator: In
                values:
                  - "basic"
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 10
        preference:
          matchExpressions:
            - key: gpu
              operator: In
              values: 
                - "true"
  containers:
  - name: myapp
    image: nginx
    ports:
      - containerPort: 80
