apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  affinity:
    # podAffinity:
      # requiredDuringSchedulingIgnoredDuringExecution:
      #   - topologyKey: kubernetes.io/hostname
      #     labelSelector:
      #       matchExpressions:
      #         - key: server
      #           operator: In
      #           values: ["nginx"]

      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: kubernetes.io/hostname
          labelSelector:
            matchExpressions:
              - key: server
                operator: In
                values: ["nginx"]
  containers:
  - name: myapp
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
